name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images to ECR
    runs-on: ubuntu-latest

    env:
      ECR_URI: ${{ secrets.ECR_REPO_URI }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Images
        run: |
          docker build -t $ECR_URI:app-latest -f Dockerfile .
          docker push $ECR_URI:app-latest

          docker build -t $ECR_URI:producer-latest -f Dockerfile .
          docker push $ECR_URI:producer-latest

          docker build -t $ECR_URI:consumer-latest -f Dockerfile .
          docker push $ECR_URI:consumer-latest

          docker build -t $ECR_URI:streamlit-latest -f Dockerfile .
          docker push $ECR_URI:streamlit-latest

  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest images and restart containers
        run: |
          docker compose pull
          docker compose up -d --remove-orphans
